version: '3'

services:

  python_app:
    container_name: flask_test
    build: .
    env_file: .env
    ports:
      - 8000:5000
    links:
      - mysqldb
    depends_on:
      mysqldb:
        condition: service_healthy

  mysqldb:
    container_name: mysql_test
    image: mysql:latest
    env_file: database.conf
    ports:
      - "32000:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s

volumes:
  db-data: