"""followers

Revision ID: 699f02225f73
Revises: ef682ca408f2
Create Date: 2021-10-12 23:02:52.376025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '699f02225f73'
down_revision = 'ef682ca408f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
